testNormalApiCall:pass
testNormalSpringCall:pass
testTimeoutCall:pass
testCatchException:java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.middleware.race.rpc.demo.test.ConsumerFunctionalTest.main(ConsumerFunctionalTest.java:26)
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.alibaba.middleware.race.rpc.demo.builder.ConsumerBuilder.testCatchException(ConsumerBuilder.java:88)
	... 5 more

testFutureCall:java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.middleware.race.rpc.demo.test.ConsumerFunctionalTest.main(ConsumerFunctionalTest.java:26)
Caused by: java.lang.AssertionError: expected:<this is a rpc framework> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.alibaba.middleware.race.rpc.demo.builder.ConsumerBuilder.testFutureCall(ConsumerBuilder.java:107)
	... 5 more

testCallback:java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.middleware.race.rpc.demo.test.ConsumerFunctionalTest.main(ConsumerFunctionalTest.java:26)
Caused by: java.lang.RuntimeException: Time out
	at com.alibaba.middleware.race.rpc.async.ResponseFuture.getResponse(ResponseFuture.java:30)
	at com.alibaba.middleware.race.rpc.api.impl.RpcConsumerImpl.asynCall(RpcConsumerImpl.java:77)
	at com.alibaba.middleware.race.rpc.demo.builder.ConsumerBuilder.testCallback(ConsumerBuilder.java:123)
	... 5 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.alibaba.middleware.race.rpc.async.ResponseFuture.getResponse(ResponseFuture.java:22)
	... 7 more

testRpcContext:pass
testConsumerHook:pass
